name: 'Document Conversion Action'
description: 'Converst documents using pandoc'
author: 'kentis'
inputs: 
  args:
    description: 'arguments to pandoc'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
